name: Build STABLE image

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-image.yml
    with:
      context: bambuddy
      image: ghcr.io/spegeli/homeassistant-app-bambuddy
    permissions:
      contents: read
      packages: write
