name: Build DAILY image

on:
  push:
    branches: [main]
    paths:
      - 'bambuddy-daily/**'
      - '.github/workflows/build-daily.yml'
      - '.github/workflows/_build-image.yml'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-image.yml
    with:
      context: bambuddy-daily
      image: ghcr.io/spegeli/addon-bambuddy-daily
    permissions:
      contents: read
      packages: write
