name: Build DAILY image

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-image.yml
    with:
      context: bambuddy-daily
      image: ghcr.io/spegeli/homeassistant-app-bambuddy-daily
    permissions:
      contents: read
      packages: write
